# -*- coding: utf-8 -*-
"""customer(2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pwP5_wgWdR4cTegwXRFEkqE4QfO3eAzf
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

np.random.seed(42)

n = 100000

data = pd.DataFrame({
    "Customer_ID": range(1, n+1),
    "Age": np.random.randint(18, 71, n),
    "Gender": np.random.choice(["Male", "Female"], n),
    "Tenure": np.random.randint(0, 11, n),
    "Balance": np.random.randint(0, 200001, n),
    "CreditScore": np.random.randint(300, 901, n),
    "EstimatedSalary": np.random.randint(10000, 150001, n),
    "NumOfProducts": np.random.randint(1, 5, n),
    "IsActiveMember": np.random.choice(["Yes", "No"], n)
})

# Simple logic to simulate churn probability
def assign_churn(row):
    score = 0

    if row["Balance"] < 50000:
        score += 1
    if row["CreditScore"] < 500:
        score += 1
    if row["Tenure"] < 2:
        score += 1
    if row["IsActiveMember"] == "No":
        score += 1
    if row["NumOfProducts"] == 1:
        score += 1

    return 1 if score >= 3 else 0

data["Churn"] = data.apply(assign_churn, axis=1)

print(data.head())
print(data.info())
print(data.describe())

print(data.isnull().sum())

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

data["Gender"] = le.fit_transform(data["Gender"])
data["IsActiveMember"] = le.fit_transform(data["IsActiveMember"])

print("Mean:\n", data.mean(numeric_only=True))
print("\nMedian:\n", data.median(numeric_only=True))
print("\nMode:\n", data.mode().iloc[0])
print("\nStandard Deviation:\n", data.std(numeric_only=True))

plt.figure()
sns.countplot(x="Churn", data=data)
plt.title("Churn Distribution")
plt.show()

plt.figure()
sns.barplot(x="Gender", y="Churn", data=data)
plt.title("Gender vs Churn")
plt.show()

plt.figure()
sns.boxplot(x="Churn", y="Age", data=data)
plt.title("Age vs Churn")
plt.show()

plt.figure()
sns.boxplot(x="Churn", y="Tenure", data=data)
plt.title("Tenure vs Churn")
plt.show()

plt.figure()
sns.boxplot(x="Churn", y="Balance", data=data)
plt.title("Balance vs Churn")
plt.show()

plt.figure()
sns.boxplot(x="Churn", y="CreditScore", data=data)
plt.title("Credit Score vs Churn")
plt.show()

plt.figure()
sns.barplot(x="IsActiveMember", y="Churn", data=data)
plt.title("Active Member vs Churn")
plt.show()

plt.figure(figsize=(10,6))
sns.heatmap(data.corr(numeric_only=True), annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

data.hist(figsize=(12,10))
plt.show()

print("Churn Rate:")
print(data["Churn"].value_counts(normalize=True) * 100)

print("\nAverage Balance of Churned Customers:")
print(data[data["Churn"] == 1]["Balance"].mean())

print("\nAverage Credit Score of Churned Customers:")
print(data[data["Churn"] == 1]["CreditScore"].mean())